# Generated by Django 5.0.1 on 2024-01-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('work', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default='+998 99 410 7441')),
                ('image', models.ImageField(upload_to='images/')),
                ('skils', models.CharField(max_length=100)),
                ('skils_1', models.CharField(max_length=100)),
                ('skils_2', models.CharField(max_length=100)),
                ('skils_3', models.CharField(max_length=100)),
                ('skils_4', models.CharField(max_length=100)),
                ('skils_5', models.CharField(max_length=100)),
                ('skils_6', models.CharField(max_length=100)),
                ('skils_7', models.CharField(max_length=100)),
                ('skils_8', models.CharField(max_length=100)),
                ('skils_9', models.CharField(max_length=100)),
                ('skils_10', models.CharField(max_length=100)),
            ],
        ),
    ]
