# Generated by Django 5.0.1 on 2024-01-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_myabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='myabout',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
