# Generated by Django 5.0.1 on 2024-01-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_myabout_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myabout',
            name='phone',
            field=models.IntegerField(blank=True, default='+998 99 410 7441', null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myabout',
            name='skils_9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
