# Generated by Django 5.0.1 on 2024-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default=1, upload_to='post/images/'),
            preserve_default=False,
        ),
    ]
