# Generated by Django 5.0.1 on 2024-01-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_portfolio_delete_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='images_1',
            field=models.ImageField(default=1, upload_to='portfolio/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='images_2',
            field=models.ImageField(default=1, upload_to='portfolio/'),
            preserve_default=False,
        ),
    ]
