# Generated by Django 5.0.1 on 2024-01-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_portfolio_images_1_portfolio_images_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_date',
            field=models.DateField(auto_now=True),
        ),
    ]
